# Generated by Django 4.2 on 2023-05-06 01:33

import PetCare_2023.common.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='', validators=[PetCare_2023.common.validators.file_max_size_in_mb]),
        ),
        migrations.AddField(
            model_name='pet',
            name='kind',
            field=models.CharField(blank=True, choices=[('Cat', 'Cat'), ('Dog', 'Dog'), ('Bunny', 'Bunny'), ('Parrot', 'Parrot'), ('Fish', 'Fish'), ('Other', 'Other')], max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='pet',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
