# Generated by Django 4.2 on 2023-05-06 21:59

import PetCare_2023.common.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0003_pet_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='mediafiles/', validators=[PetCare_2023.common.validators.file_max_size_in_mb]),
        ),
    ]
