# Generated by Django 4.2 on 2023-06-20 23:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0007_alter_pet_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pet',
            old_name='user',
            new_name='owner_id',
        ),
    ]
