# Generated by Django 4.2 on 2023-06-26 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0012_alter_pet_image_alter_pet_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pet',
            old_name='owner',
            new_name='owner_id',
        ),
    ]
