# Generated by Django 4.2 on 2023-06-26 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0013_rename_owner_pet_owner_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pet',
            old_name='owner_id',
            new_name='user',
        ),
    ]
