# Generated by Django 4.2 on 2023-06-28 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0019_alter_pet_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pet',
            old_name='user',
            new_name='owner_id',
        ),
    ]
